version: '3.1'

volumes:
  db:
    {}

networks:
  frontend:
    external: true
  backend:
    driver: bridge


services:
  web:
    restart: always
    image: pbc/httpd:alpine
    build:
      context: .
      dockerfile: Dockerfile.httpd
    volumes:
    - ${PWD}:/var/www/html
    env_file:
    - ./.env
    expose:
    - "80"
    labels:
    - "traefik.frontend.rule=Host:${SERVER_NAME}"
    - "traefik.docker.network=frontend"
    networks:
    - frontend
    - backend

  code:
    restart: always
    build: .
    env_file:
    - ./.env
    image: pbc/laravel:latest
    environment:
      ServerName: ${SERVER_NAME}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DOCKER: "TRUE"
      DOCKER_HOST: "web"
    volumes:
      - ${PWD}:/var/www/html/
    expose:
      - "9000"
    networks:
      - backend

  db:
    restart: always
    image: mysql:5.5
    env_file:
    - ./.env
    volumes:
      - db:/var/lib/mysql/
      - ${PWD}/database/dump/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      explicit_defaults_for_timestamp: 1
      TIMESTAMP: NOT NULL
    ports:
      - "3306"
    networks:
      - backend

  firefox:
    image: travix/selenium-node-firefox:latest
    privileged: true
    ports:
      - "4444:4444"
    environment:
      - GRID_TIMEOUT=120000
      - GRID_BROWSER_TIMEOUT=120000
      - no_proxy=localhost
      - TZ=America/Chicago
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    expose:
      - '4444'
    depends_on:
      - code
    networks:
      - backend

  redis:
    image: redis:3
    restart: always
    expose:
      - '6379'
    networks:
      - backend
    #TODO: redis conf file for security


