version: '3.1'

volumes:
  db:
    {}

networks:
  frontend:
    external: true
  backend:
    driver: bridge
  testend:
    driver: bridge


services:
  web:
    restart: always
    image: pbc/httpd:alpine
    build:
      context: .
      dockerfile: Dockerfile.httpd
    volumes:
    - ${PWD}:/var/www/html
    env_file:
    - ./.env
    expose:
    - "80"
    labels:
    - "traefik.frontend.rule=Host:${SERVER_NAME}"
    - "traefik.docker.network=frontend"
    networks:
    - frontend
    - backend
    - testend

  code:
    restart: always
    build: .
    env_file:
    - ./.env
    image: pbc/laravel:latest
    environment:
      ServerName: ${SERVER_NAME}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}
      DOCKER: "TRUE"
      DOCKER_HOST: "web"
    volumes:
      - ${PWD}:/var/www/html/
    expose:
      - "9000"
    networks:
      - backend

  db:
    restart: always
    image: mysql:5.5
    env_file:
    - ./.env
    volumes:
      - db:/var/lib/mysql/
      - ${PWD}/database/dump/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      explicit_defaults_for_timestamp: 1
      TIMESTAMP: NOT NULL
    ports:
      - "3306"
    networks:
      - backend

#  hub:
#    image: selenium/hub
#    privileged: true
#    ports:
#      - "4444:4444"
#    environment:
#      - GRID_TIMEOUT=120000
#      - GRID_BROWSER_TIMEOUT=120000
#    networks:
#      - testend
#      - backend
#    depends_on:
#      - code

#  chrome:
#    image: selenium/node-chrome-debug
##    image: selenium/standalone-chrome-debug
#    environment:
#      - no_proxy=localhost
#      - TZ=America/Chicago
#      - HUB_PORT_4444_TCP_ADDR=hub
#      - HUB_PORT_4444_TCP_PORT=4444
#    expose:
#      - '4444'
#      - '5900'
#    depends_on:
#      - hub
#    links:
#      - hub
#    networks:
#      - testend

  firefox:
#    image: selenium/node-firefox-debug #to uncomment out with hub
    image: selenium/standalone-firefox-debug #to comment out with hub
    privileged: true #to comment out with hub
    ports: #to comment out with hub
      - "4444:4444" #to comment out with hub
    environment:
      - GRID_TIMEOUT=120000 #to comment out
      - GRID_BROWSER_TIMEOUT=120000 #to comment out with hub
      - no_proxy=localhost
      - TZ=America/Chicago
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    expose:
      - '4444'
    depends_on:
#      - hub #to uncomment out with hub
      - code #to comment out with hub
#    links: #to uncomment out with hub
#      - hub #to uncomment out with hub
    networks:
      - testend
      - backend #to comment out with hub

  redis:
    image: redis:3
    restart: always
    expose:
      - '6379'
    networks:
      - backend
    #TODO: redis conf file for security


